config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :pictures do
    collection do
      post :confirm
    end
  end
  
  get '/' , to: 'pictures#index'
  get 'favorites', to: 'pictures#favorites'
  
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/inbox"
  end
  
  resources :users, only: [:new, :create, :show, :update]
  resources :sessions, only: [:new, :create, :destroy]
  resources :favorites, only: [:create, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :picture
end

app/models/picture.rb
class Picture < ApplicationRecord
  mount_uploader :image, ImageUploader
  
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  
  belongs_to :user, optional: true
  
  validates :content, presence: true
  validates :image, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  
  with_options if: :password do |user|
    user.validates :password, 
      on: :create,
      presence: { message: "パスワードを入力して下さい" },
      length: { minimum: 6 },
      confirmation: { allow_blank: true } 
    user.validates :password, 
      on: :update,
      presence: { message: "新しいパスワードを入力して下さい" },
      length: { minimum: 6 },
      confirmation: { allow_blank: true }
  end
  
  validates :name, presence: true, length: { maximum: 30 }
   validates :email, presence: true, length: { maximum: 100 },
     format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  
  
  has_many :favorites, dependent: :destroy
  has_many :favorite_pictures, through: :favorites, source: :picture
  
  has_many :pictures
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  
  # 例外処理
  rescue_from ActiveRecord::RecordNotFound, with: :render_404
  rescue_from ActionController::RoutingError, with: :render_404
  rescue_from Exception, with: :render_500

  def render_404
    render template: 'errors/error_404', status: 404, layout: 'application', content_type: 'text/html'
  end

  def render_500
    render template: 'errors/error_500', status: 500, layout: 'application', content_type: 'text/html'
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    pic_id = params[:picture_id]
    favorite = current_user.favorites.create(picture_id: pic_id)
    if params[:from_show] != "true"
      redirect_to pictures_url #, notice: "#{favorite.picture.user.name}さんのブログをお気に入り登録しました"
    else
      redirect_to picture_path(pic_id)
    end
  end
  
  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    pic_id = favorite.picture.id
    if params[:from_show] != "true"
      redirect_to pictures_url #, notice: "#{favorite.picture.user.name}さんのブログをお気に入り解除しました"
    else
      redirect_to picture_path(pic_id)
    end
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :check_login, only: [:new, :confirm, :create, :favorites]
  def index
    @pictures = Picture.all
  end
  
  def new
    if params[:back]
      @picture = Picture.new(picture_params)
    else
      @picture = Picture.new
    end
  end
  
  def confirm 
    @picture = Picture.new(picture_params)
    render :new if @picture.invalid?
  end
  
  def create
    @picture = Picture.new(picture_params)
    @picture.user_id = current_user.id
    
    if @picture.save
      #メール送信
      PictureMailer.picture_mail(@picture).deliver
      # 一覧画面へ遷移して"ブログを作成しました！"とメッセージを表示します。
      redirect_to pictures_path, notice: "投稿しました！"
    else
      render "new"
    end
  end
  
  def show 
    @picture = Picture.find(params[:id])
  end
  
  def edit
    @picture = Picture.find(params[:id]);
  end
  
  def update
    @picture = Picture.find(params[:id]);
    if @picture.update(picture_params)
      redirect_to pictures_path
    else
      render 'edit'
    end
    
  end
  
  def destroy 
    @picture = Picture.find(params[:id]);
    @picture.destroy
    redirect_to pictures_path
  end
  
  def favorites
    @favorites = Favorite.where(user_id: current_user.id)
  end
  
  
  private
  def picture_params
    params.require(:picture).permit(:content, :image, :image_cache)
  end
  def check_login
    if logged_in?
    else
      redirect_to new_session_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to pictures_path
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render 'new'
    end
  end
  
  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to pictures_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    
  end
  
  def create
    @user = User.new(user_params)
    
    if @user.save
      redirect_to user_path(@user.id)
    else
      render 'new'
    end
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :image, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_pictures_path
    elsif action_name == 'edit'
      picture_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instaclone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="mainContainer">
    <header>
<nav class="navbar navbar-expand-sm bg-light navbar-light">
  <a class="navbar-brand" href="/">Instaclone</a>
  <!-- Links -->
  <ul class="navbar-nav">
    <% if logged_in? %>
    <% current_user %>
    <li class="nav-item">
      <%= link_to current_user.email, user_path(@current_user), { :class => "nav-link"}  %>
    </li>
    <li class="nav-item">
      <%= link_to "新規投稿", new_picture_path, { :class => "nav-link"}  %>
    </li>
    <li class="nav-item">
      <%= link_to "お気に入り", favorites_path, { :class => "nav-link"}  %>
    </li>
    <li class="nav-item">
      <%= link_to "ログアウト" , session_path(@current_user), {:class => "nav-link", :method => "delete"} %>
    </li>
    <% else %>
    <li class="nav-item">
      <%= link_to "ログイン", new_session_path, { :class => "nav-link"}  %>
    </li>
    <li class="nav-item">
      <%= link_to "新規登録", new_user_path, { :class => "nav-link"}  %>
    </li>
    <% end %>
  </ul>

</nav>
  </header>
  <div>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
  </div>
    <%= yield %>
  <footer class="footer">
    Copyright(C) 2018- Instaclone
  </footer>
  </div>
  </body>
</html>

app/views/pictures/_form.html.erb
<%= form_with(model: @picture, local: true, url: choose_new_or_edit) do |form| %>
  <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= @picture.errors.count %>件のエラーがあります。</h2>
      <ul>

      <% @picture.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="picture_form">
    <div class="picture_image">
      <p><%= image_tag(@picture.image.url) if @picture.image.url %></p>
      <p><%= form.file_field :image, id: :picture_image %></p>
      <%= form.hidden_field :image_cache %>
    </div>
    <div class="picture_content">
      <%= form.label :content ,:class => "picture_label" %>
      <%= form.text_area :content, :class => "picture_textarea" ,:size => "100x10" %>
    </div>
    <%= form.submit %>
  </div>
<% end %>

app/views/pictures/confirm.html.erb
<h3>以下の内容で、送信する。</h3>

<%= form_with(model: @picture, url: pictures_path, local: true) do |form| %>
  <%= form.hidden_field :image_cache %>
  <%= form.hidden_field :content %>
  <div class="picture_form">
    <div class="picture_image">
  <%= image_tag(@picture.image.url) if @picture.image.url %>
    </div>
  </div>
  <p>コメント:<%= @picture.content %></p>
  <%= form.submit  "投稿する" %>
<% end %>

<%= form_with(model: @picture, url: new_picture_path, local: true, method: 'get') do |form| %>
  <%= form.hidden_field :content %>
  <%= form.hidden_field :image_cache %>
  <%= form.submit "もどる", name: 'back' %>
<% end %>

app/views/pictures/edit.html.erb
<h2>編集</h2>

<%= render 'form' %>

app/views/pictures/favorites.html.erb
<div class="favorites_list">
<table class="table table-bordered">
  <thead>
    <tr>
    <th>picture_id</th>
    <th>user_name</th>
    <th>content</th>
    </tr>
  </thead>
  <tbody>
<% @favorites.each do |f| %>

<tr>
  <td><%= link_to f.picture.id, picture_path(f.picture.id) %></td>
  <td><%= f.picture.user.name %></td>
  <td><%= f.picture.content %></td>
</tr>

<% end %>
<% if @favorites.length == 0 %>
<tr>
  <td colspan="3">ないです。</td>
</tr>
<% end %>
</tbody>
</table>
</div>

app/views/pictures/index.html.erb
<div class="container">
<div class="row">
<div class="col-sm-8 center-block">
  <div class="container">
    <div class="row">
<% @pictures.each do |p| %>
      
      <div class="posts col-sm-12">
        <p><%= p.user.name %></p>
        <div class="post_image">
          <a href="<%= picture_path(p.id) %>" class="link_to_post">
          <%= image_tag p.image.url %>
         </a>
        </div>
        <div class="post_content">
          <p><%= p.content %></p>
        </div>
        <% if logged_in? %>
        <% if p.user != current_user %>
        <div class="favbtn">
        <% @favorite = current_user.favorites.find_by(picture_id: p.id) %>
          <% if @favorite.present? %>
            <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
          <% else %>
            <%= link_to 'お気に入りする', favorites_path(picture_id: p.id), method: :post, class: 'btn btn-primary' %>
         <% end %>
        </div>
        <% else %>
        <div class="editbtn btn btn-primary">
          <%= link_to "編集", edit_picture_path(p.id) %>
        </div>
        <div class="deletebtn btn btn-primary">
          <%= link_to "削除", picture_path(p.id), method: :delete %>
        </div>
        <% end %>
        <% end %>
      </div>
<% end %>
    </div>
  </div>
</div>
</div></div>

app/views/pictures/new.html.erb
 <h2>ブログを作成する</h2>

 <%= render 'form' %>

app/views/pictures/show.html.erb
<div class="container posts">
  <div class="">
    <%= @picture.user.name %>
  </div>
  <div class="post_image">
    <%= image_tag @picture.image.url %>
  </div>
  <div class="post_content">
    <%= @picture.content %>
  </div>
  <div>
    <% if @picture.user != current_user && logged_in? %>
        <div class="favbtn">
        <% @favorite = current_user.favorites.find_by(picture_id: @picture.id) %>
          <% if @favorite.present? %>
            <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id, from_show: true), method: :delete, class: 'btn btn-danger' %>
          <% else %>
            <%= link_to 'お気に入りする', favorites_path(picture_id: @picture.id, from_show: true), method: :post, class: 'btn btn-primary' %>
         <% end %>
        </div>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<h1>Sign up</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>  
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "Create my account" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>

<p>メールアドレス: <%= @user.email %></p>